name: build-dist

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    if: "${{ contains(github.event.pull_request.labels.*.name, 'autorelease: pending') }}"

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.9

      - run: bun install --frozen-lockfile
      - run: bun run build

      - name: Commit dist outputs
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: 'chore: rebuild dist for release'
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
